services:
    akki.payzen.form.type.gateway_configuration:
        class: Akki\SyliusPayumPayzenPlugin\Form\Type\PayzenGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: payzen, label: akki.payzen.gateway_label }
            - { name: form.type }

    akki.payzen.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Akki\SyliusPayumPayzenPlugin\Gateway\PayzenGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: payzen }

    akki.payzen.extension.from_foreign_gateway:
        public: true
        class: Akki\SyliusPayumPayzenPlugin\Extension\FromForeignGatewayExtension
        tags:
            - name: payum.extension
              factory: payzen